### ISSUE TITLE
srs auto down,why

### ISSUE THREAD

**Issue by auqf** [ossrs/srs#1157]
hi, i found my srs often auto down, the logs as follows:
Jun 12 03:13:01 ai kernel: srs[19244]: segfault at 38 ip 00007fb920a704d8 sp 00007fff7c8f73c0 error 4 in libstdc++.so.6[7fb92099e000+17e000]
Jun 12 03:13:02 ai abrt[22981]: Saved core dump of pid 19244 (/usr/local/srs/objs/srs) to /var/spool/abrt/ccpp-2018-06-12-03:13:01-19244 (8155136 bytes)
Jun 12 03:13:02 ai abrtd: Directory 'ccpp-2018-06-12-03:13:01-19244' creation detected
Jun 12 03:13:02 ai abrtd: Executable '/usr/local/srs/objs/srs' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Jun 12 03:13:02 ai abrtd: 'post-create' on '/var/spool/abrt/ccpp-2018-06-12-03:13:01-19244' exited with 1
Jun 12 03:13:02 ai abrtd: Deleting problem directory '/var/spool/abrt/ccpp-2018-06-12-03:13:01-19244'

**Comment by auqf** [comment]
add:
the follows is the gdb debug info
(gdb) bt
#0  std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
    at /usr/local/src/build_gcc_5.4.0/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h:2690
#1  0x000000000049b34b in SrsHls::dispose (this=0x25a3ed0) at src/app/srs_app_hls.cpp:1166
#2  0x000000000048760f in SrsSource::dispose (this=0x25a2a10) at src/app/srs_app_source.cpp:1021
#3  0x000000000048671e in SrsSource::dispose_all () at src/app/srs_app_source.cpp:798
#4  0x000000000047368e in SrsServer::dispose (this=0x257ad90) at src/app/srs_app_server.cpp:560
#5  0x0000000000475b2e in SrsServer::cycle (this=0x257ad90) at src/app/srs_app_server.cpp:877
#6  0x00000000005276f2 in run_master () at src/main/srs_main_server.cpp:414
#7  0x0000000000527520 in run () at src/main/srs_main_server.cpp:379
#8  0x00000000005271b6 in main (argc=3, argv=0x7fffb5ccc048) at src/main/srs_main_server.cpp:334
