### ISSUE TITLE
I got a core dump when use in ubuntu x64 14.04,gcc 4.8

### ISSUE THREAD

**Issue by luowuf** [ossrs/srs#1162]
I got a core dump when use in ubuntu x64 14.04,gcc 4.8.

I have run it about 48 hours

please give me some help.

Send frame 15940505610,enc_ctx=0x7df700
Write packet 15940109610 15940109610 (size= 6533)
[2018-06-24 19:11:41.94] sent packet: time=-1239759574, size=6533, b[4]=0x41(P)
Send frame 15940149210,enc_ctx=0x7df700
Write packet 15940113210 15940113210 (size= 5860)

Program received signal SIGPIPE, Broken pipe.
0x00007ffff4664fd0 in __libc_writev (fd=13, vector=0x1adc780, count=92)
    at ../sysdeps/unix/sysv/linux/writev.c:54
54	../sysdeps/unix/sysv/linux/writev.c: No such file or directory.
(gdb) bt
#0  0x00007ffff4664fd0 in __libc_writev (fd=13, vector=0x1adc780, count=92)
    at ../sysdeps/unix/sysv/linux/writev.c:54
#1  0x000000000040f035 in srs_hijack_io_writev (
    ctx=<error reading variable: Cannot access memory at address 0x7fffffffd4c8>, 
    ctx@entry=<error reading variable: Cannot access memory at address 0x7fffffffd4f8>, 
    iov=<error reading variable: Cannot access memory at address 0x7fffffffd4c0>, iov_size=92, nwrite=0x0)
    at src/libs/srs_lib_simple_socket.cpp:226
(gdb) q
A debugging session is active.

**Comment by winlinvip** [comment]
srslibrtmp?
