### ISSUE TITLE
求指导：使用srs-librtmp推流，如果sps数据打乱后，推流 崩溃点在::writev

### ISSUE THREAD

**Issue by ibanezsc** [ossrs/srs#1192]
Thread 2 "go_arm" received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7fb6bdd040 (LWP 579)]
0x000000000051cbfc in writev () at ../sysdeps/unix/syscall-template.S:86
86      ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x000000000051cbfc in writev () at ../sysdeps/unix/syscall-template.S:86
#1  0x000000000040c5c0 in srs_hijack_io_writev (ctx=0x609440, iov=0x77d250, iov_size=1024, nwrite=0x0) at src/libs/srs_lib_simple_socket.cpp:226
#2  0x000000000040d1f0 in SimpleSocketStream::writev (this=0x609410, iov=0x77d250, iov_size=1024, nwrite=0x0) at src/libs/srs_lib_simple_socket.cpp:385
#3  0x0000000000450a18 in srs_write_large_iovs (skt=0x609410, iovs=0x779250, size=3934, pnwrite=0x0) at src/protocol/srs_rtmp_utility.cpp:270
#4  0x000000000042e02c in SrsProtocol::do_iovs_send (this=0x609510, iovs=0x779250, size=3934) at src/protocol/srs_rtmp_stack.cpp:606
#5  0x000000000042dff4 in SrsProtocol::do_send_messages (this=0x609510, msgs=0x7fb6bdc4e0, nb_msgs=1) at src/protocol/srs_rtmp_stack.cpp:546
#6  0x000000000042f7e4 in SrsProtocol::send_and_free_messages (this=0x609510, msgs=0x7fb6bdc4e0, nb_msgs=1, stream_id=1) at src/protocol/srs_rtmp_stack.cpp:884
#7  0x000000000042f6c8 in SrsProtocol::send_and_free_message (this=0x609510, msg=0x7fb00008c0, stream_id=1) at src/protocol/srs_rtmp_stack.cpp:858
#8  0x0000000000433964 in SrsRtmpClient::send_and_free_message (this=0x6094b0, msg=0x7fb00008c0, stream_id=1) at src/protocol/srs_rtmp_stack.cpp:2001
#9  0x0000000000406b78 in srs_rtmp_write_packet (rtmp=0x6091b0, type=9 '\t', timestamp=3, data=0x7fb003e070 "\027\001", size=251692) at src/libs/srs_librtmp.cpp:1090
#10 0x0000000000407420 in srs_write_h264_ipb_frame (context=0x6091b0, frame=0x7fb63a0014 "e\270", frame_size=251683, dts=3, pts=3) at src/libs/srs_librtmp.cpp:1334
#11 0x00000000004078b8 in srs_write_h264_raw_frame (context=0x6091b0, frame=0x7fb63a0014 "e\270", frame_size=251683, dts=3, pts=3) at src/libs/srs_librtmp.cpp:1437
#12 0x0000000000407a94 in srs_h264_write_raw_frames (rtmp=0x6091b0, frames=0x7fb63a0010 "", frames_size=251687, dts=3, pts=3) at src/libs/srs_librtmp.cpp:1478

**Comment by winlinvip** [comment]
SPS数据打乱是什么意思？能否提供个文件包含打乱的SPS？

**Comment by ibanezsc** [comment]
就是正常的h264帧，故意把sps帧的某几个字节的数据改掉，i和p帧不变。（例如00 00 00 01 67 **01 02 03 04 05 06** 。。。）其中01 02 03 04 05 06是故意改变后的数据，sps帧的其他字节可以不变。）
然后调用srs_librtmp发送给srs.在发送I帧的时候出现推送端出现崩溃

**Comment by winlinvip** [comment]
应该是解析SPS没有检查边界。
