### ISSUE TITLE
coredump occurs when tracing srs with systemtap

### ISSUE THREAD

**Issue by zengxiaobai** [ossrs/srs#1307]
srs version： 2.0release 
srs_debug.stap
```
probe process("/usr/local/srs/objs/srs").function("*").call
{
    printf("%s -> %s\n", thread_indent(4), ppfunc());
}

probe process("/usr/local/srs/objs/srs").function("*").return
{
    printf("%s <- %s\n", thread_indent(-4), ppfunc());
}
```

stap -g -v -d "/lib64/libstdc++.so.6" -d "/usr/local/srs/objs/srs" -d "/lib64/libgcc_s.so.1" -d "/lib64/ld-linux-x86-64.so.2" -d "/lib64/libdl.so.2" -d "/lib64/libc.so.6" srs_debug.stap -o ./srs3.debug

after a while the coredump follow occurs, can you give me some help to trace srs with systemtap, what is the meaning of the coredump?

```
(gdb) bt
#0  0x00007fd64cb651f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fd64cb668e8 in __GI_abort () at abort.c:90
#2  0x00007fd64cb5e266 in __assert_fail_base (fmt=0x7fd64ccb0e68 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x5ee9a8 "thread->state == 1", file=file@entry=0x5ee9a0 "sched.c", 
    line=line@entry=123, function=function@entry=0x5eea30 <__PRETTY_FUNCTION__.3834> "_st_vp_schedule")
    at assert.c:92
#3  0x00007fd64cb5e312 in __GI___assert_fail (assertion=0x5ee9a8 "thread->state == 1", file=0x5ee9a0 "sched.c", 
    line=123, function=0x5eea30 <__PRETTY_FUNCTION__.3834> "_st_vp_schedule") at assert.c:101
#4  0x00000000005175d5 in _st_vp_schedule () at sched.c:123
#5  0x00007fffffffe000 in ?? ()
#6  0x0000000000000000 in ?? ()
(gdb) f 4
#4  0x00000000005175d5 in _st_vp_schedule () at sched.c:123
123	  ST_ASSERT(thread->state == _ST_ST_RUNNABLE);
(gdb) p thread
$1 = (_st_thread_t *) 0x7fd64db1fe30
(gdb) p *thread
$2 = {state = 0, flags = 2, start = 0x517851 <_st_idle_thread_start>, arg = 0x0, retval = 0x1, 
  stack = 0x20c8080, links = {next = 0x8a3ff0 <_st_this_vp+16>, prev = 0x8a3ff0 <_st_this_vp+16>}, wait_links = {
    next = 0x0, prev = 0x0}, tlink = {next = 0x20c8108, prev = 0x8a4020 <_st_this_vp+64>}, due = 0, left = 0x0, 
  right = 0x0, heap_index = 0, private_data = 0x7fd64db1ff80, term = 0x0, context = {{__jmpbuf = {4096, 
        140558403239248, 6220577, 1000, 0, 0, 140558403239216, 140737488347136}, __mask_was_saved = 0, 
      __saved_mask = {__val = {0 <repeats 16 times>}}}}}
```

**Comment by hy05190134** [comment]
@zengxiaobai  why use systemmap to trace srs

**Comment by winlinvip** [comment]
Why not GDB?
