### ISSUE TITLE
SRS3 crash

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#1482]
```
#3  0x00007f835ab8a810 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000004e7660 in SrsHls::on_audio (this=0xb3d0220, shared_audio=0x7f8357bcfb20, format=0xb7f5330) at src/app/srs_app_hls.cpp:1205
#5  0x00000000004d1ee8 in SrsOriginHub::on_audio (this=0xb54cd80, shared_audio=0x7f8357bcfb20) at src/app/srs_app_source.cpp:964
#6  0x00000000004d816f in SrsSource::on_audio_imp (this=0xb3f2340, msg=0x7f8357bcfb20) at src/app/srs_app_source.cpp:2124
#7  0x00000000004d7d62 in SrsSource::on_audio (this=0xb3f2340, shared_audio=0xb559fd0) at src/app/srs_app_source.cpp:2074
#8  0x00000000004cc1e7 in SrsRtmpConn::process_publish_message (this=0xb871100, source=0xb3f2340, msg=0xb559fd0) at src/app/srs_app_rtmp_conn.cpp:1001
#9  0x00000000004cc0c9 in SrsRtmpConn::handle_publish_message (this=0xb871100, source=0xb3f2340, msg=0xb559fd0) at src/app/srs_app_rtmp_conn.cpp:980
#10 0x00000000005726ae in SrsPublishRecvThread::consume (this=0x7f8357c177f0, msg=0xb559fd0) at src/app/srs_app_recv_thread.cpp:389
#11 0x00000000005712f1 in SrsRecvThread::do_cycle (this=0x7f8357c177f8) at src/app/srs_app_recv_thread.cpp:146
#12 0x000000000057114d in SrsRecvThread::cycle (this=0x7f8357c177f8) at src/app/srs_app_recv_thread.cpp:115
#13 0x00000000004fa7f2 in SrsSTCoroutine::cycle (this=0xb59c140) at src/app/srs_app_st.cpp:198
#14 0x00000000004fa867 in SrsSTCoroutine::pfn (arg=0xb59c140) at src/app/srs_app_st.cpp:213
#15 0x00000000005abbce in _st_thread_main () at sched.c:327
#16 0x00000000005ac368 in st_thread_create (start=0x7f8357c17560, arg=0x94baa8, joinable=0, stk_size=9747104) at sched.c:591

(gdb) p format->acodec
$2 = (SrsAudioCodecConfig *) 0x0
```

**Comment by winlinvip** [comment]
```
(gdb) bt
#0  0x00007f241a0f1625 in raise () from /lib64/libc.so.6
#1  0x00007f241a0f2e05 in abort () from /lib64/libc.so.6
#2  0x00007f241a0ea74e in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f241a0ea810 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000004e7660 in SrsHls::on_audio (this=0xa92ff60, shared_audio=0x7f2417bdfb20, format=0xa93a350) at src/app/srs_app_hls.cpp:1205
#5  0x00000000004d1ee8 in SrsOriginHub::on_audio (this=0xa95fbf0, shared_audio=0x7f2417bdfb20) at src/app/srs_app_source.cpp:964
#6  0x00000000004d816f in SrsSource::on_audio_imp (this=0xa92ec10, msg=0x7f2417bdfb20) at src/app/srs_app_source.cpp:2124
#7  0x00000000004d7d62 in SrsSource::on_audio (this=0xa92ec10, shared_audio=0xa8e7a50) at src/app/srs_app_source.cpp:2074
#8  0x00000000004cc1e7 in SrsRtmpConn::process_publish_message (this=0xa9e12c0, source=0xa92ec10, msg=0xa8e7a50) at src/app/srs_app_rtmp_conn.cpp:1001
#9  0x00000000004cc0c9 in SrsRtmpConn::handle_publish_message (this=0xa9e12c0, source=0xa92ec10, msg=0xa8e7a50) at src/app/srs_app_rtmp_conn.cpp:980
#10 0x00000000005726ae in SrsPublishRecvThread::consume (this=0x7f2417d597f0, msg=0xa8e7a50) at src/app/srs_app_recv_thread.cpp:389
#11 0x00000000005712f1 in SrsRecvThread::do_cycle (this=0x7f2417d597f8) at src/app/srs_app_recv_thread.cpp:146
#12 0x000000000057114d in SrsRecvThread::cycle (this=0x7f2417d597f8) at src/app/srs_app_recv_thread.cpp:115
#13 0x00000000004fa7f2 in SrsSTCoroutine::cycle (this=0xa95e200) at src/app/srs_app_st.cpp:198
#14 0x00000000004fa867 in SrsSTCoroutine::pfn (arg=0xa95e200) at src/app/srs_app_st.cpp:213
#15 0x00000000005abbce in _st_thread_main () at sched.c:327
#16 0x00000000005ac368 in st_thread_create (start=0x7f2417d59560, arg=0x94baa8, joinable=0, stk_size=9747104) at sched.c:591
#17 0x00007f2417d8fe90 in ?? ()
#18 0x0000000417d59590 in ?? ()
#19 0x0000000affffffff in ?? ()
#20 0x000000000a8a28dc in ?? ()
#21 0x0000000000000000 in ?? ()
(gdb) f 4
#4  0x00000000004e7660 in SrsHls::on_audio (this=0xa92ff60, shared_audio=0x7f2417bdfb20, format=0xa93a350) at src/app/srs_app_hls.cpp:1205
1205	    srs_assert(format->acodec);
(gdb) p format
$1 = (SrsFormat *) 0xa93a350
(gdb) p format->acodec
$2 = (SrsAudioCodecConfig *) 0x0
```

**Comment by winlinvip** [comment]
Fixed.
