### ISSUE TITLE
录制mp4时crash

### ISSUE THREAD

**Issue by liuchizhen** [ossrs/srs#1779]
问题描述：
录制mp4时程序crash。数据流方向为内网192.168.50.3接入rtmp流并forwad到192.168.50.4（录制成mp4），此机器操作系统Ubuntu 16.04.6 LTS。在另一套测试机中（操作系统Ubuntu 14.04）同样的部署同样的配置同样的媒体流数据无崩溃现象。

1. SRS版本：3.0Release。

2. Crash日志如下：

```
2020-05-25 19:25:53.427][Trace][10006][552] RTMP client ip=192.168.50.5, fd=8
[2020-05-25 19:25:53.440][Trace][10006][552] complex handshake success
[2020-05-25 19:25:53.440][Trace][10006][552] connect app, tcUrl=rtmp://192.168.50.4:8084/srs, pageUrl=, swfUrl=, schema=rtmp, vhost=192.168.50.4, port=8084, app=srs, args=(obj)
[2020-05-25 19:25:53.440][Trace][10006][552] edge-srs ip=192.168.50.5, version=3.0.140, pid=17222, id=593
[2020-05-25 19:25:53.440][Trace][10006][552] protocol in.buffer=0, in.ack=0, out.ack=0, in.chunk=128, out.chunk=128
[2020-05-25 19:25:53.478][Trace][10006][552] client identified, type=flash-publish, vhost=192.168.50.4, app=srs, stream=0001, param=?vhost=192.168.50.4, duration=0ms
[2020-05-25 19:25:53.478][Trace][10006][552] connected stream, tcUrl=rtmp://192.168.50.4:8084/srs, pageUrl=, swfUrl=, schema=rtmp, vhost=__defaultVhost__, port=8084, app=srs, stream=0001, param=?vhost=192.168.50.4, args=(obj)
[2020-05-25 19:25:53.478][Trace][10006][552] source url=/srs/0001, ip=192.168.50.5, cache=1, is_edge=0, source_id=-1[-1]
[2020-05-25 19:25:53.479][Trace][10006][552] dvr stream 0001 to file /data/media/srs/dvr/__defaultVhost__/srs/2020052519/0001/2020-05-25-19-25-53.mp4
[2020-05-25 19:25:53.479][Trace][10006][552] ignore disabled exec for vhost=__defaultVhost__
[2020-05-25 19:25:53.479][Trace][10006][552] start publish mr=0/350, p1stpt=20000, pnt=5000, tcp_nodelay=0

Program received signal SIGSEGV, Segmentation fault.
0x00000000005b5e99 in SrsDvrMp4Segmenter::encode_video (this=0xa3ba20, video=0xa3ea10, format=0xa3aa00) at src/app/srs_app_dvr.cpp:503
503	    SrsVideoAvcFrameType frame_type = format->video->frame_type;
(gdb) bt
#0  0x00000000005b5e99 in SrsDvrMp4Segmenter::encode_video (this=0xa3ba20, video=0xa3ea10, format=0xa3aa00) at src/app/srs_app_dvr.cpp:503
#1  0x00000000005b3f65 in SrsDvrSegmenter::write_video (this=0xa3ba20, shared_video=0x7ffff7f33b00, format=0xa3aa00) at src/app/srs_app_dvr.cpp:161
#2  0x00000000005b6a53 in SrsDvrPlan::on_video (this=0xa3b7a0, shared_video=0x7ffff7f33b00, format=0xa3aa00) at src/app/srs_app_dvr.cpp:665
#3  0x00000000005b84d3 in SrsDvr::on_video (this=0xa3ab00, shared_video=0x7ffff7f33b00, format=0xa3aa00) at src/app/srs_app_dvr.cpp:1023
#4  0x00000000004e007c in SrsOriginHub::on_video (this=0xa39ef0, shared_video=0x7ffff7f33b00, is_sequence_header=false)
    at src/app/srs_app_source.cpp:1087
#5  0x00000000004e5fa5 in SrsSource::on_video_imp (this=0xa39f70, msg=0x7ffff7f33b00) at src/app/srs_app_source.cpp:2306
#6  0x00000000004e5bf9 in SrsSource::on_video (this=0xa39f70, shared_video=0xa3cfc0) at src/app/srs_app_source.cpp:2261
#7  0x00000000004d8fa7 in SrsRtmpConn::process_publish_message (this=0xa2fe50, source=0xa39f70, msg=0xa3cfc0) at src/app/srs_app_rtmp_conn.cpp:1021
#8  0x00000000004d8dce in SrsRtmpConn::handle_publish_message (this=0xa2fe50, source=0xa39f70, msg=0xa3cfc0) at src/app/srs_app_rtmp_conn.cpp:993
#9  0x00000000005810b6 in SrsPublishRecvThread::consume (this=0x7ffff7f69800, msg=0xa3cfc0) at src/app/srs_app_recv_thread.cpp:389
#10 0x000000000057fbd4 in SrsRecvThread::do_cycle (this=0x7ffff7f69808) at src/app/srs_app_recv_thread.cpp:146
#11 0x000000000057fa25 in SrsRecvThread::cycle (this=0x7ffff7f69808) at src/app/srs_app_recv_thread.cpp:115
#12 0x0000000000509c88 in SrsSTCoroutine::cycle (this=0xa3c970) at src/app/srs_app_st.cpp:198
#13 0x0000000000509cfd in SrsSTCoroutine::pfn (arg=0xa3c970) at src/app/srs_app_st.cpp:213
#14 0x00000000005bdd9d in _st_thread_main () at sched.c:337
#15 0x00000000005be515 in st_thread_create (start=0xa3ada0, arg=0x7ffff7f69530, joinable=32767, stk_size=-134834912) at sched.c:616
#16 0x00007ffff7f69e30 in ?? ()
#17 0x0000000000a3cbbc in ?? ()
#18 0x00000000f7f69580 in ?? ()
#19 0xffffffff00000002 in ?? ()
#20 0x0000000300000003 in ?? ()
#21 0x0000000000a2dc08 in ?? ()
#22 0x00000000009f5360 in ?? ()
#23 0x00007ffff7f69590 in ?? ()
#24 0x00000000005bd719 in _st_vp_schedule () at sched.c:132
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) p format->video
$1 = (SrsVideoFrame *) 0x0
```

3.录制配置

```
listen              8084;
max_connections     1000;
pid                 ./objs/srs.slave.pid;
daemon              off;
srs_log_tank        console;
srs_log_level       verbose;
vhost __defaultVhost__ {
    dvr {
        enabled      on;
        dvr_apply    all;
        dvr_path     /data/media/srs/dvr/[vhost]/[app]/[2006][01][02][15]/[stream]/[2006]-[01]-[02]-[15]-[04]-[05].mp4;
        dvr_plan     session;
        dvr_wait_keyframe  on;
        time_jitter  full;
    }
}
```

**Comment by winlinvip** [comment]
Check it.

**Comment by winlinvip** [comment]
信息太少，无法定位，将删除这个issue。
