### ISSUE TITLE
GB28181,大华设备推流几个小时内产生coredump

### ISSUE THREAD

**Issue by callmefisher** [ossrs/srs#1910]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
大华摄像头，视频编码格式H.264H,分辨率1920 * 1080 (1080p),FPS: 25, 固定码流2048Kbs, I帧间隔50，推流2个小时内，srs会产生崩溃
1. SRS版本(Version): `4.0.37`
1. SRS的日志如下(Log):
```
corrupted size vs. prev_size: 0x0000000002546920 ***

Frame 13
,崩溃堆栈信息SrsPsStreamDemixer::on_ps_stream
info args
this = 0x16e84b0
ps_data = 0x1ae3120 ""
ps_size = 23492
timestamp = 174272400
ssrc = 0,

info locals
 err= {_vptr.SrsCplxError = 0x88bf70 <vtable for SrsCplxError+16>, code = 6019, wrapped = 0x0,
  msg = "h264 frame size", func = "write_h264_ipb_frame2", file = "src/app/srs_app_gb28181.cpp",
  line = 1336, cid = {_vptr._SrsContextId = 0x88bed0 <vtable for _SrsContextId+16>,
    v_ = "er1axs70"}, rerrno = 11, desc = "", _summary = ""}

video_stream = {_vptr.SrsSimpleStream = 0x891b30 <vtable for SrsSimpleStream+16>,
  data = std::vector of length 23464, capacity 23464
audio_stream = {_vptr.SrsSimpleStream = 0x891b30 <vtable for SrsSimpleStream+16>,
  data = std::vector of length 0, capacity 0}

next_ps_pack = 0x1ae8ce4 ".\210\241,
video_pts = 174261690
audio_pts = 0
pse_index = 1
__FUNCTION__ = "on_ps_stream"
complete_len = 23492
incomplete_len = 0

bt

#0  0x00007fc0ab6f1ccb in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007fc0ab6f3668 in _Unwind_Backtrace () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007fc0ab42ec0f in __GI___backtrace (array=array@entry=0x7fc0ab11ee40, size=size@entry=64)
    at ../sysdeps/x86_64/backtrace.c:110
#3  0x00007fc0ab3389f5 in backtrace_and_maps (do_abort=<optimized out>, do_abort@entry=2,
    written=<optimized out>, fd=fd@entry=9) at ../sysdeps/unix/sysv/linux/libc_fatal.c:47
#4  0x00007fc0ab3907f5 in __libc_message (do_abort=2,
    fmt=fmt@entry=0x7fc0ab4a9f98 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:172
#5  0x00007fc0ab399e0b in malloc_printerr (ar_ptr=0x7fc0ab6ddb20 <main_arena>, ptr=0x18df120,
    str=0x7fc0ab4a6d35 "corrupted size vs. prev_size", action=3) at malloc.c:5020
#6  _int_free (av=0x7fc0ab6ddb20 <main_arena>, p=<optimized out>, have_lock=0) at malloc.c:4021
#7  0x00007fc0ab39d58c in __GI___libc_free (mem=<optimized out>) at malloc.c:2975
#8  0x0000000000423862 in __gnu_cxx::new_allocator<char>::deallocate (this=0x7fc0ab11fa28,
    __p=0x18d9580 "") at /usr/include/c++/4.8/ext/new_allocator.h:110
#9  0x000000000042334c in std::_Vector_base<char, std::allocator<char> >::_M_deallocate (
    this=0x7fc0ab11fa28, __p=0x18d9580 "", __n=23464) at /usr/include/c++/4.8/bits/stl_vector.h:174
#10 0x0000000000423102 in std::_Vector_base<char, std::allocator<char> >::~_Vector_base (
    this=0x7fc0ab11fa28, __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/stl_vector.h:160
#11 0x0000000000422b9a in std::vector<char, std::allocator<char> >::~vector (this=0x7fc0ab11fa28,
    __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/stl_vector.h:416
#12 0x0000000000434383 in SrsSimpleStream::~SrsSimpleStream (this=0x7fc0ab11fa20,
    __in_chrg=<optimized out>) at src/kernel/srs_kernel_stream.cpp:35
---Type <return> to continue, or q <return> to quit---
#13 0x000000000062ab6c in SrsPsStreamDemixer::on_ps_stream (this=0x16e84b0, ps_data=0x1ae3120 "",
    ps_size=23492, timestamp=174272400, ssrc=0) at src/app/srs_app_gb28181.cpp:910
#14 0x000000000062c8ac in SrsGb28181RtmpMuxer::do_cycle (this=0x16e8360)
    at src/app/srs_app_gb28181.cpp:1166
#15 0x000000000062d512 in SrsGb28181RtmpMuxer::cycle (this=0x16e8360)
    at src/app/srs_app_gb28181.cpp:1280
#16 0x0000000000522983 in SrsSTCoroutine::cycle (this=0x16e2930) at src/app/srs_app_st.cpp:206
#17 0x0000000000522a11 in SrsSTCoroutine::pfn (arg=0x16e2930) at src/app/srs_app_st.cpp:221
#18 0x000000000065714d in _st_thread_main () at sched.c:337
#19 0x00000000006578bd in st_thread_create (start=0x7fc000000000, arg=0x0, joinable=32704,
    stk_size=-1422497475) at sched.c:616
#20 0x0000000000000001 in ?? ()
#21 0x0000000000000000 in ?? ()

```
1. SRS的配置如下(Config):
```
stream_caster {
    enabled             on;
    caster              gb28181;
    audio_enable        on;
    wait_keyframe       on;
    jitterbuffer_enable  on;
    auto_create_channel   off;
}
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `大华设备推流，2个小时内，一定崩溃`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)
稳定

**Comment by lishus718** [comment]
@callmefisher 哥们，你这个问题怎么解决的？
我现在有同样的问题。core文件都一摸一样
