### ISSUE TITLE
[Patch] srs crash when pushing vp6 video

### ISSUE THREAD

**Issue by microelec** [ossrs/srs#2082]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0   3cf3047f97ce8c898f8285b4171fe34a1d685479`
1. SRS的日志如下(Log):
```
#0  0x0000000000632e70 in SrsRtcFromRtmpBridger::filter (this=0xedc080, msg=0x7ffff7fb9a70, format=0xedd3f0, has_idr=@0x7ffff7fb996f: false, 
    samples=std::vector of length 0, capacity 0) at src/app/srs_app_rtc_source.cpp:881
#1  0x0000000000632a69 in SrsRtcFromRtmpBridger::on_video (this=0xedc080, msg=0x7ffff7fb9a70) at src/app/srs_app_rtc_source.cpp:816
#2  0x000000000050b78d in SrsSource::on_video_imp (this=0xedd770, msg=0x7ffff7fb9a70) at src/app/srs_app_source.cpp:2361
#3  0x000000000050b290 in SrsSource::on_video (this=0xedd770, shared_video=0xf092f0) at src/app/srs_app_source.cpp:2311
#4  0x00000000004fd84d in SrsRtmpConn::process_publish_message (this=0xe0cf30, source=0xedd770, msg=0xf092f0) at src/app/srs_app_rtmp_conn.cpp:1050
#5  0x00000000004fd67b in SrsRtmpConn::handle_publish_message (this=0xe0cf30, source=0xedd770, msg=0xf092f0) at src/app/srs_app_rtmp_conn.cpp:1022
#6  0x00000000005b4f64 in SrsPublishRecvThread::consume (this=0xeda200, msg=0xf092f0) at src/app/srs_app_recv_thread.cpp:395
#7  0x00000000005b3991 in SrsRecvThread::do_cycle (this=0xeda208) at src/app/srs_app_recv_thread.cpp:150
#8  0x00000000005b37fa in SrsRecvThread::cycle (this=0xeda208) at src/app/srs_app_recv_thread.cpp:119
#9  0x000000000052c959 in SrsSTCoroutine::cycle (this=0xf2d670) at src/app/srs_app_st.cpp:226
#10 0x000000000052c9e7 in SrsSTCoroutine::pfn (arg=0xf2d670) at src/app/srs_app_st.cpp:241
#11 0x00000000006480d2 in _st_thread_main () at sched.c:337
#12 0x000000000064884a in st_thread_create (start=0x57bf38 <std::_Rb_tree_node<std::pair<int const, SrsStageInfo*> >::_M_valptr() const+28>, 
    arg=0xed9ea0, joinable=0, stk_size=15630128) at sched.c:616
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```
1. SRS的配置如下(Config):
```
rtc.conf
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `srs -c rtc.conf`
1. `push vp6 video by FMLE`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

```
format->video==NULL，
在for循环的处理format->video->nb_samples，需要容错保护。

srs_error_t SrsRtcFromRtmpBridger::filter(SrsSharedPtrMessage* msg, SrsFormat* format, bool& has_idr, vector<SrsSample*>& samples)
{
    srs_error_t err = srs_success;

    // If IDR, we will insert SPS/PPS before IDR frame.
    if (format->video && format->video->has_idr) {
        has_idr = true;
    }

    // Update samples to shared frame.
    for (int i = 0; i < format->video->nb_samples; ++i) {
        SrsSample* sample = &format->video->samples[i];

        // Because RTC does not support B-frame, so we will drop them.
        // TODO: Drop B-frame in better way, which not cause picture corruption.
        if (discard_bframe) {
            if ((err = sample->parse_bframe()) != srs_success) {
                return srs_error_wrap(err, "parse bframe");
            }
            if (sample->bframe) {
                continue;
            }
        }

        samples.push_back(sample);
    }

    return err;
}
```

**Comment by winlinvip** [comment]
赞Patch。

**Comment by winlinvip** [comment]
Won't fix. Reason: VP6 is removed.
