### ISSUE TITLE
在头文件中fowrad decalaration "class SrsServer"  ,没有在对应的cpp文件中包含srs_app_server.hpp头文件导致运行是调用其on_unpublish指向了不同的函数。

### ISSUE THREAD

**Issue by sureone** [ossrs/srs#2860]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

class SrsServer 在头文件中fowrad decalaration ,没有在引用的cpp文件中包含srs_app_server.hpp头文件导致运行时调用其on_unpublish函数时指向了错误的函数。

当前版本在srs_app_gb28181.hpp前向声明了class SrsServer, 在 srs_app_gb28181.cpp中没有include "srs_app_server.hpp“, 导致在srs_app_source.cpp调用on_unpublish函数时指向了错误的函数

"src/app/srs_app_source.cpp" 2677 行
    handler->on_unpublish(this, req);

运行结果如下
```
2558	    handler->on_unpublish(this, req);
(gdb) s
ISrsReloadHandler::on_reload_max_conns (this=0x5555560e8bc0) at src/app/srs_app_reload.cpp:33
33	    return srs_success;
(gdb) bt
#0  ISrsReloadHandler::on_reload_max_conns (this=0x5555560e8bc0) at src/app/srs_app_reload.cpp:33
#1  0x00005555556f336a in SrsLiveSource::on_unpublish (this=0x55555614e3f0) at src/app/srs_app_source.cpp:2558
#2  0x000055555583502f in SrsGb28181RtmpMuxer::close (this=0x5555560e95c0) at src/app/srs_app_gb28181.cpp:1676
#3  0x000055555583095a in SrsGb28181RtmpMuxer::~SrsGb28181RtmpMuxer (this=0x5555560e95c0, __in_chrg=<optimized out>) at src/app/srs_app_gb28181.cpp:828
#4  0x0000555555830db6 in SrsGb28181RtmpMuxer::~SrsGb28181RtmpMuxer (this=0x5555560e95c0, __in_chrg=<optimized out>) at src/app/srs_app_gb28181.cpp:846
#5  0x00005555556d2962 in SrsResourceManager::do_clear (this=0x5555560f2790) at src/app/srs_app_conn.cpp:344
#6  0x00005555556d25d2 in SrsResourceManager::clear (this=0x5555560f2790) at src/app/srs_app_conn.cpp:310
#7  0x00005555556d131a in SrsResourceManager::cycle (this=0x5555560f2790) at src/app/srs_app_conn.cpp:103
#8  0x0000555555714baa in SrsFastCoroutine::cycle (this=0x5555560f2940) at src/app/srs_app_st.cpp:272
#9  0x0000555555714c46 in SrsFastCoroutine::pfn (arg=0x5555560f2940) at src/app/srs_app_st.cpp:287
#10 0x000055555586e0d6 in _st_thread_main () at sched.c:365
#11 0x000055555586e949 in st_thread_create (start=0xffffffffffffff90, arg=0x22030, joinable=21845, stk_size=1443639304) at sched.c:667
#12 0x0000000000000007 in ?? ()
#13 0x0000000000000020 in ?? ()
#14 0x00005555560b2010 in ?? ()
#15 0x0000000000000040 in ?? ()
#16 0xffffffffffffff90 in ?? ()
#17 0x0000000000000000 in ?? ()
```

如果include了 头文件，可以正确调用到SrsServer::on_unpublish函数：

```
2558	    handler->on_unpublish(this, req);
(gdb) s
SrsServer::on_unpublish (this=0x5555560e8bc0, s=0x55555614d540, r=0x5555561425e0) at src/app/srs_app_server.cpp:1747
1747	    http_server->http_unmount(s, r);
(gdb) bt
#0  SrsServer::on_unpublish (this=0x5555560e8bc0, s=0x55555614d540, r=0x5555561425e0) at src/app/srs_app_server.cpp:1747
#1  0x00005555556f336a in SrsLiveSource::on_unpublish (this=0x55555614d540) at src/app/srs_app_source.cpp:2558
#2  0x000055555583504b in SrsGb28181RtmpMuxer::close (this=0x5555560e95c0) at src/app/srs_app_gb28181.cpp:1677
#3  0x000055555583095a in SrsGb28181RtmpMuxer::~SrsGb28181RtmpMuxer (this=0x5555560e95c0, __in_chrg=<optimized out>) at src/app/srs_app_gb28181.cpp:829
#4  0x0000555555830db6 in SrsGb28181RtmpMuxer::~SrsGb28181RtmpMuxer (this=0x5555560e95c0, __in_chrg=<optimized out>) at src/app/srs_app_gb28181.cpp:847
#5  0x00005555556d2962 in SrsResourceManager::do_clear (this=0x5555560f2670) at src/app/srs_app_conn.cpp:344
#6  0x00005555556d25d2 in SrsResourceManager::clear (this=0x5555560f2670) at src/app/srs_app_conn.cpp:310
#7  0x00005555556d131a in SrsResourceManager::cycle (this=0x5555560f2670) at src/app/srs_app_conn.cpp:103
#8  0x0000555555714baa in SrsFastCoroutine::cycle (this=0x5555560f2820) at src/app/srs_app_st.cpp:272
#9  0x0000555555714c46 in SrsFastCoroutine::pfn (arg=0x5555560f2820) at src/app/srs_app_st.cpp:287
#10 0x000055555586e0f2 in _st_thread_main () at sched.c:365
#11 0x000055555586e965 in st_thread_create (start=0xffffffffffffff90, arg=0x22030, joinable=21845, stk_size=1443639304) at sched.c:667
#12 0x0000000000000007 in ?? ()
#13 0x0000000000000020 in ?? ()
#14 0x00005555560b2010 in ?? ()
#15 0x0000000000000040 in ?? ()
#16 0xffffffffffffff90 in ?? ()
#17 0x0000000000000000 in ?? ()

```

> 描述你遇到了什么问题(Please description your issue here)
1. SRS版本(Version): `xxcxxxx`

commit 72ad5267738e2895ee5deb5c041bcc7a2d157551 (HEAD, old-origin/feature/gb28181)

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

通过sip invite 和 sip bye来打开和关闭流来触发此场景。
1. curl 'http://192.168.1.232:1985/api/v1/gb28181?action=sip_invite&id=32010000001110000004&chid=32010000001310000001'
2. curl 'http://192.168.1.232:1985/api/v1/gb28181?action=sip_bye&id=32010000001110000004&chid=32010000001310000001'

**Comment by sureone** [comment]
多态情况下，指针的强制转换引入的问题，已通过简单的程序验证。

**Comment by phusinh** [comment]
Currently, I run web rtc in forward model, but the slaves only run in 1 cpu, wasting the rest of the cpu. Is there any other solution to solve this? Let the slaves have the same ip and the same port to run on the same ports. different cpu. Thank you. Have a nice day.

**Comment by winlinvip** [comment]
GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

由于265主要在GB中使用，所以265分支也迁移到了 [srs-gb28181](https://github.com/ossrs/srs-gb28181/tree/feature/h265)

该Issue会被删除，请先阅读FAQ：#2716
