### ISSUE TITLE
signaling信令服务器异常

### ISSUE THREAD

**Issue by starise-wg** [ossrs/srs#3074]
**signaling信令服务器异常退出**

> signaling信令服务器异常退出中断

1. SRS Version(版本): `4.0.251`

1. signaling Log(日志):
```
warn] 2022/06/22 15:04:54.841343 [1][1202] Ignore err EOF for 159.75.247.221:59594
[trace] 2022/06/22 15:04:54.841411 [1][1202] Remove client display=nksscadmin, room=570927
[trace] 2022/06/22 15:04:56.081663 [1][1203] Serve client 159.75.247.221:59606 at /sig/v1/rtc?room=570927&display=nksscadmin
[trace] 2022/06/22 15:04:56.488719 [1][1203] Join display=nksscadmin, room=570927 ok
[trace] 2022/06/22 15:04:57.265989 [1][1203] Remove client display=nksscadmin, room=570927
[warn] 2022/06/22 15:04:57.265943 [1][1203] Ignore err EOF for 159.75.247.221:59606
[trace] 2022/06/22 15:04:58.411623 [1][1204] Serve client 159.75.247.221:59610 at /sig/v1/rtc?room=570927&display=nksscadmin
[trace] 2022/06/22 15:04:58.796431 [1][1204] Join display=nksscadmin, room=570927 ok
[trace] 2022/06/22 15:05:04.857220 [1][1205] Serve client 159.75.247.221:59620 at /sig/v1/rtc?room=386093&display=nksscadmin
[trace] 2022/06/22 15:05:05.181393 [1][1205] Join display=nksscadmin, room=386093 ok
[warn] 2022/06/22 15:05:06.805760 [1][1205] Ignore err EOF for 159.75.247.221:59620
[trace] 2022/06/22 15:05:06.805820 [1][1205] Remove client display=nksscadmin, room=386093
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x66240a]
goroutine 1817 [running]:
main.main.func3.3.1(0xc0007b6000, 0x53, 0x4000, 0x0, 0x0)
        /tmp/signaling/main.go:289 +0x88a
main.main.func3.3(0xc00030ae70, 0xc00009ad20, 0xc00057f500, 0xc0004b4330, 0x73a1b8, 0xc000762b80, 0xc00057f4a0)
        /tmp/signaling/main.go:332 +0x16e
created by main.main.func3
        /tmp/signaling/main.go:229 +0x3ed
```
1. SRS Config(配置):

```
listen 1935;
max_connections 1000;
srs_log_tank file;
srs_log_file ./conf/log/hrtc.log;
daemon on;
http_api {
    enabled on;
    listen 1985;
    raw_api {
        enabled on;
        allow_reload on;
        allow_query on;
        allow_update on;
    }
    https {
        enabled on;
        listen 443;
        key ./conf/fan_huanjianit.com_NGINX.key;
        cert ./conf/fan_huanjianit.com_NGINX.crt;
    }
}
http_server {
    enabled on;
    listen 8080;
    dir ./objs/nginx/html;
    https {
        enabled on;
        listen 1990;
        key ./conf/fan_huanjianit.com_NGINX.key;
        cert ./conf/fan_huanjianit.com_NGINX.crt;
    }
}
stats {
    network 0;
    disk sda sdb xvda xvdb vda;
}
rtc_server {
    enabled on;
    listen 8000;
    candidate 159.75.247.221;
}
vhost __defaultVhost__ {
	http_hooks {
        enabled         on;
        on_connect      https://mdv.huanjianit.com/hjkj-video-center/srsCallback/onConnectCallBack;
        on_close        https://mdv.huanjianit.com/hjkj-video-center/srsCallback/onCloseCallBack;
        on_publish      https://mdv.huanjianit.com/hjkj-video-center/srsCallback/onPublishCallBack;
        on_unpublish    https://mdv.huanjianit.com/hjkj-video-center/srsCallback/onUnpublishCallBack;
        on_play         https://mdv.huanjianit.com/hjkj-video-center/srsCallback/onPlayCallBack;
        on_stop         https://mdv.huanjianit.com/hjkj-video-center/srsCallback/onStopCallBack;
    }
    tcp_nodelay on;
    min_latency on;
    dvr {
        enabled on;
        dvr_path ./objs/nginx/html/record/[app]/[stream]/[2006]/[01]/[02]/[15]:[04]:[05].mp4;
        dvr_plan session;
        dvr_duration 10;
        dvr_wait_keyframe on;
        dvr_apply all;
    }
    hls {
        enabled on;
    }
    rtc {
        enabled on;
        bframe discard;
        #rtc_to_rtmp on;
		rtmp_to_rtc on;
    }
    http_remux {
        enabled on;
        mount [vhost]/[app]/[stream].flv;
    }
    play {
        gop_cache off;
        queue_length 10;
        mw_latency 100;
    }
    publish {
        mr off;
    }
}

```

**signaling正常运行**

> signaling正常运行

**Comment by winlinvip** [comment]
这个Signaling就是个demo。

这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、OBS、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
