### ISSUE TITLE
2.0.200，SRS crash, thread cycle failed.

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#546]
```
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004bbf98 in internal::SrsThread::thread_cycle (this=0x210f390) at src/app/srs_app_thread.cpp:239
239	        disposed = true;
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.107.el6.x86_64 libgcc-4.4.7-3.el6.x86_64 libstdc++-4.4.7-3.el6.x86_64
(gdb) bt
#0  0x00000000004bbf98 in internal::SrsThread::thread_cycle (this=0x210f390) at src/app/srs_app_thread.cpp:239
#1  0x00000000004bbff7 in internal::SrsThread::thread_fun (arg=0x210f390) at src/app/srs_app_thread.cpp:247
#2  0x000000000054a90a in _st_thread_main () at sched.c:327
#3  0x000000000054b0a4 in st_thread_create (start=0x54b81e <st_usleep+202>, arg=0x7eff69480b40, joinable=32511, stk_size=1758600752) at sched.c:591
#4  0x00000000004bba41 in internal::SrsThread::start (this=Cannot access memory at address 0x7ffffffd9
) at src/app/srs_app_thread.cpp:109
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) 
```

**Comment by winlinvip** [comment]
```
(gdb) f 1
#1  0x00000000004bbff7 in internal::SrsThread::thread_fun (arg=0x210f390) at src/app/srs_app_thread.cpp:247
247	        obj->thread_cycle();
(gdb) p obj[0]
Cannot access memory at address 0x210f390
```

可见这个obj已经被释放过了的。
