### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by jarod** [ossrs/srs#552]
貌似是#509 还没完全修复
```bash
$ ./objs/srs -v
2.0.205

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
部署情况跟#509 中一样，报这个错的是edge服务器

**Comment by winlinvip** [comment]
那肯定是野指针导致内存破坏引起的了，这种是最难查的bug。。。

**Comment by winlinvip** [comment]
再给一下core文件吧，binary和core都给出来。

**Comment by jarod** [comment]
core dump http://pan.baidu.com/s/1dEgXOU9

**Comment by winlinvip** [comment]
-rw-------.  1 winlin winlin 2.2G Dec 25 20:59 core.27676
看起来srs的连接数不算太少，都2.2G内存了。

不过看core文件，和#509是不一样的。
```

[winlin@centos7 srs]$ gdb objs/srs -c core.27676 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/winlin/git/srs/trunk/objs/srs...done.
[New LWP 27676]
Core was generated by `./objs/srs -c ./conf/edge.conf'.
Program terminated with signal 6, Aborted.
#0  0x00007f2f8f2475f7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.1.x86_64 libgcc-4.8.5-4.el7.x86_64 libstdc++-4.8.5-4.el7.x86_64
(gdb) bt
#0  0x00007f2f8f2475f7 in raise () from /lib64/libc.so.6
#1  0x00007f2f8f248ce8 in abort () from /lib64/libc.so.6
#2  0x00007f2f8fb4b9d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007f2f8fb49946 in ?? () from /lib64/libstdc++.so.6
#4  0x00007f2f8fb49973 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x00007f2f8fb49b93 in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x00007f2f8fb4a12d in operator new(unsigned long) () from /lib64/libstdc++.so.6
#7  0x00007f2f8fb4a1c9 in operator new[](unsigned long) () from /lib64/libstdc++.so.6
#8  0x0000000000409956 in SrsCommonMessage::create_payload (this=0x42de060, size=4161)
    at src/kernel/srs_kernel_flv.cpp:173
#9  0x00000000004313a3 in SrsProtocol::read_message_payload (this=0x21e9a90, chunk=0x3d62120, pmsg=0x7f2f56fdba60)
    at src/protocol/srs_rtmp_stack.cpp:1421
#10 0x00000000004303e3 in SrsProtocol::recv_interlaced_message (this=0x21e9a90, pmsg=0x7f2f56fdbae0)
    at src/protocol/srs_rtmp_stack.cpp:979
#11 0x000000000042e0c5 in SrsProtocol::recv_message (this=0x21e9a90, pmsg=0x7f2f56fdbbb8)
    at src/protocol/srs_rtmp_stack.cpp:365
#12 0x0000000000433f08 in SrsRtmpClient::recv_message (this=0x2197c80, pmsg=0x7f2f56fdbbb8)
    at src/protocol/srs_rtmp_stack.cpp:1955
#13 0x00000000004fae8e in SrsEdgeIngester::ingest (this=0x16d1220) at src/app/srs_app_edge.cpp:193
#14 0x00000000004faae6 in SrsEdgeIngester::cycle (this=0x16d1220) at src/app/srs_app_edge.cpp:160
#15 0x00000000004a4f45 in SrsReusableThread2::cycle (this=0xb57c20) at src/app/srs_app_thread.cpp:538
#16 0x00000000004a3f3f in internal::SrsThread::thread_cycle (this=0x2ce7090) at src/app/srs_app_thread.cpp:206
#17 0x00000000004a4151 in internal::SrsThread::thread_fun (arg=0x2ce7090) at src/app/srs_app_thread.cpp:249
#18 0x0000000000518492 in _st_thread_main () at sched.c:327
#19 0x0000000000518c02 in st_thread_create (start=
    0x477d92 <std::vector<std::string, std::allocator<std::string> >::_M_range_check(unsigned long) const+28>, 
    arg=0x7f2f5488d750, joinable=0, stk_size=9825928) at sched.c:591
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) 
```

**Comment by winlinvip** [comment]
查看各个堆栈：
```

(gdb) f 8
#8  0x0000000000409956 in SrsCommonMessage::create_payload (this=0x42de060, size=4161)
    at src/kernel/srs_kernel_flv.cpp:173
173	    payload = new char[size];
(gdb) p *this
$3 = {_vptr.SrsCommonMessage = 0x890c10 <vtable for SrsCommonMessage+16>, header = {
    _vptr.SrsMessageHeader = 0x890c50 <vtable for SrsMessageHeader+16>, timestamp_delta = 1989332, 
    payload_length = 4161, message_type = 9 '\t', stream_id = 1, timestamp = 1989332, perfer_cid = 7}, size = 0, 
  payload = 0x0}
```
这个msg本身是没有问题的，payload的大小4161也没有问题。

**Comment by winlinvip** [comment]
上一级堆栈：
```

(gdb) f 9
#9  0x00000000004313a3 in SrsProtocol::read_message_payload (this=0x21e9a90, chunk=0x3d62120, pmsg=0x7f2f56fdba60)
    at src/protocol/srs_rtmp_stack.cpp:1421
1421	        chunk->msg->create_payload(chunk->header.payload_length);
(gdb) p *this
$4 = {_vptr.SrsProtocol = 0x8938f0 <vtable for SrsProtocol+16>, skt = 0x2a44370, 
  requests = std::map with 2 elements = {[1] = "connect", [2] = "createStream"}, 
  chunk_streams = std::map with 0 elements, cs_cache = 0xcd6860, in_buffer = 0x23bc590, in_chunk_size = 60000, 
  in_ack_size = {ack_window_size = 2500000, acked_size = 27518438}, auto_response_when_recv = true, 
  manual_response_queue = std::vector of length 0, capacity 0, out_iovs = 0x26854b0, nb_out_iovs = 256, 
  out_c0c3_caches = "\a\vԜ\000\022\320\t\001\000\000\000\005\v\324\304\000\000k\b\001\000\000\000\005\v\324\330\000\000k\b\001\000\000\000\005\v\324\354\000\000k\b\001\000\000\000\005\v\325\000\000\000k\b\001\000\000\000\005\v\325\024\000\000k\b\001\000\000\000\a\v\325\062\000\fv\t\001\000\000\000\005\v\325Z\000\000k\b\001\000\000\000\005\v\325n\000\000k\b\001\000\000\000\005\vՂ\000\000k\b\001\000\000\000\005\vՖ\000\000k\b\001\000\000\000\005\vժ\000\000k\b\001\000\000\000\a\v\325\321\000\r\004\t\001\000\000\000\005\v\325\371\000\000k\b\001\000\000\000\005\v\326\r\000\000k\b\001\000\000\000\005\v\326!\000\000k\b\001\000\000\000\005\v\326\065\000\000k\b\001\000\000\000"..., 
  warned_c0c3_cache_dry = false, out_chunk_size = 60000}

(gdb) p *chunk
$5 = {_vptr.SrsChunkStream = 0x8938b0 <vtable for SrsChunkStream+16>, fmt = 0 '\000', cid = 7, header = {
    _vptr.SrsMessageHeader = 0x890c50 <vtable for SrsMessageHeader+16>, timestamp_delta = 1989332, 
    payload_length = 4161, message_type = 9 '\t', stream_id = 1, timestamp = 1989332, perfer_cid = 7}, 
  extended_timestamp = false, msg = 0x42de060, msg_count = 15846}

(gdb) p payload_size
$6 = 4161
(gdb) p in_chunk_size
$7 = 60000
```
协议栈也未见异常。

**Comment by winlinvip** [comment]
上一级堆栈：
```
(gdb) f 12
#12 0x0000000000433f08 in SrsRtmpClient::recv_message (this=0x2197c80, pmsg=0x7f2f56fdbbb8)
    at src/protocol/srs_rtmp_stack.cpp:1955
1955	    return protocol->recv_message(pmsg);
(gdb) p *this
$21 = {_vptr.SrsRtmpClient = 0x893730 <vtable for SrsRtmpClient+16>, hs_bytes = 0x0, protocol = 0x21e9a90, 
  io = 0x2a44370}

(gdb) p *(SrsStSocket*)io
$24 = {<ISrsProtocolReaderWriter> = {<ISrsProtocolReader> = {<ISrsBufferReader> = {
        _vptr.ISrsBufferReader = 0x897e40 <vtable for SrsStSocket+96>}, <ISrsProtocolStatistic> = {
        _vptr.ISrsProtocolStatistic = 0x897ed0 <vtable for SrsStSocket+240>}, <No data fields>}, <ISrsProtocolWriter> = {<ISrsBufferWriter> = {
        _vptr.ISrsBufferWriter = 0x897f38 <vtable for SrsStSocket+344>}, <No data fields>}, <No data fields>}, 
  recv_timeout = 3000000, send_timeout = 30000000, recv_bytes = 29384666, send_bytes = 4175, stfd = 0xd0d4c0}
(gdb) p (*(SrsStSocket*)io).stfd[0]
$25 = {osfd = 101, inuse = 1, private_data = 0x0, destructor = 0x0, aux_data = 0x0, next = 0x0}
```
这个是个客户端（边缘回源链接），socket都没有异常。

**Comment by winlinvip** [comment]
再往上：
```
(gdb) f 13
#13 0x00000000004fae8e in SrsEdgeIngester::ingest (this=0x16d1220) at src/app/srs_app_edge.cpp:193
193	        if ((ret = client->recv_message(&msg)) != ERROR_SUCCESS) {
(gdb) p *this
$26 = {<ISrsReusableThread2Handler> = {_vptr.ISrsReusableThread2Handler = 0x89ae70 <vtable for SrsEdgeIngester+16>}, 
  stream_id = 1, _source = 0x2c39a70, _edge = 0x3db2e30, _req = 0x1fec450, pthread = 0xb57c20, stfd = 0xd0d4c0, 
  io = 0x2a44370, kbps = 0x25d5980, client = 0x2197c80, origin_index = 0}
(gdb) p _req[0]
$27 = {_vptr.SrsRequest = 0x893870 <vtable for SrsRequest+16>, ip = "58.49.163.0", 
  tcUrl = "xxx", 
  pageUrl = "xxx", swfUrl = "http://xxx", 
  objectEncoding = 3, schema = "rtmp", vhost = "__defaultVhost__", host = "www.513fd.com", port = "1935", 
  app = "live", param = "?token=xxx&time=1451043084", stream = "0-xx-xx", 
  duration = -1, args = 0x0}
(gdb) 
```

没有见到异常。

**Comment by winlinvip** [comment]
系统资源信息：
```
(gdb) p _srs_system_meminfo
$30 = {ok = true, sample_time = 1451048380730, percent_ram = 0.366692573, percent_swap = 0.00710161636, 
  MemActive = 12164920, RealInUse = 5961632, NotInUse = 10296216, MemTotal = 16257848, MemFree = 4092928, 
  Buffers = 0, Cached = 6203288, SwapTotal = 8265724, SwapFree = 8207024}
(gdb) p _srs_system_cpu_system_stat
$31 = {ok = true, sample_time = 1451048383732, percent = 0.0111790765, total_delta = 4741, user = 16487720, 
  nice = 14201, sys = 10116367, idle = 1901622640, iowait = 100253, irq = 7923, softirq = 1271155, steal = 0, 
  guest = 0}
(gdb) p _srs_system_cpu_self_stat
$32 = {ok = true, sample_time = 1451048383732, percent = 0.0932711512, pid = 27676, 
  comm = "(srs)", '\000' <repeats 26 times>, state = 82 'R', ppid = 1, pgrp = 27641, session = 31251, tty_nr = 34820, 
  tpgid = 31251, flags = 4219200, minflt = 474883, cminflt = 0, majflt = 0, cmajflt = 0, utime = 69024, 
  stime = 59080, cutime = 0, cstime = 0, priority = 20, nice = 0, num_threads = 1, itrealvalue = 0, 
  starttime = 119167623, vsize = 2538868736, rss = 73268, rsslim = 18446744073709551615, startcode = 4194304, 
  endcode = 6880852, startstack = 140734230998640, kstkesp = 139842258246824, kstkeip = 139842242451920, signal = 0, 
  blocked = 0, sigignore = 4096, sigcatch = 18435, wchan = 0, nswap = 0, cnswap = 0, exit_signal = 17, processor = 2, 
  rt_priority = 0, policy = 0, delayacct_blkio_ticks = 0, guest_time = 0, cguest_time = 0}
(gdb) p _srs_system_rusage
$33 = {ok = true, sample_time = 1451048383732, r = {ru_utime = {tv_sec = 690, tv_usec = 244518}, ru_stime = {
      tv_sec = 590, tv_usec = 805215}, {ru_maxrss = 293072, __ru_maxrss_word = 293072}, {ru_ixrss = 0, 
      __ru_ixrss_word = 0}, {ru_idrss = 0, __ru_idrss_word = 0}, {ru_isrss = 0, __ru_isrss_word = 0}, {
      ru_minflt = 474883, __ru_minflt_word = 474883}, {ru_majflt = 0, __ru_majflt_word = 0}, {ru_nswap = 0, 
      __ru_nswap_word = 0}, {ru_inblock = 0, __ru_inblock_word = 0}, {ru_oublock = 7440, __ru_oublock_word = 7440}, {
      ru_msgsnd = 0, __ru_msgsnd_word = 0}, {ru_msgrcv = 0, __ru_msgrcv_word = 0}, {ru_nsignals = 0, 
      __ru_nsignals_word = 0}, {ru_nvcsw = 3120361, __ru_nvcsw_word = 3120361}, {ru_nivcsw = 278464, 
      __ru_nivcsw_word = 278464}}}
```
除了内存占用了36%，貌似也没有见到异常。

**Comment by winlinvip** [comment]
查看服务器信息：
```
(gdb) p _source[0]
$36 = {<ISrsReloadHandler> = {_vptr.ISrsReloadHandler = 0x896330 <vtable for SrsSource+16>}, static pool = {_M_t = {
      _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, SrsSource*> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, SrsSource*> > >> = {<No data fields>}, <No data fields>}, 
        _M_key_compare = {<std::binary_function<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0xfe1f00, _M_left = 0x241fa00, _M_right = 0xda8b50}, 
        _M_node_count = 118}}}, _source_id = 62546, _req = 0x1fec450, 
  consumers = std::vector of length 62, capacity 256 = {0x15333c0, 0x2ba0930, 0x393bf70, 0x5bbd090, 0x22db180, 
    0x2abc960, 0x2baf9e0, 0x3f70850, 0x1b27320, 0x41ef190, 0x3c233e0, 0xd16fe0, 0x3599d70, 0xd95cd0, 0x2f50750, 
    0x3d695b0, 0x2ba75d0, 0x35e0ed0, 0x2dc75d0, 0x1a10240, 0x40c4330, 0x21d9c10, 0x2bfa360, 0x4b1b4d0, 0x4e51820, 
    0x475f5f0, 0x2b2af80, 0x5b10ac0, 0x4ca5930, 0x3202290, 0x4d31c90, 0xe03a50, 0x2c27590, 0x2f68240, 0x2acc0e0, 
    0x2e44f20, 0x3aeb250, 0x37b9a40, 0x23e60c0, 0x115d660, 0x41e0530, 0x3776890, 0x3e20f90, 0xd00ba0, 0x3d670a0, 
    0x3b96f70, 0x30adf10, 0x1c9d640, 0x1bb2ff0, 0x1b2cbe0, 0x1a9e790, 0x19dcf80, 0x4f518c0, 0x27d7600, 0x21ed980, 
    0x30ad890, 0x25c3660, 0x3c3eb50, 0x4f52f10, 0x14ea2a0, 0xd94cd0, 0x2be3dd0}, 
  jitter_algorithm = SrsRtmpJitterAlgorithmFULL, mix_correct = false, mix_queue = 0x22798c0, 
  is_monotonically_increase = false, last_packet_time = 1989319, hls = 0x23ea550, dvr = 0x21cc580, encoder = 
    0x4368690, hds = 0x13fe550, play_edge = 0x3db2e30, publish_edge = 0xf41710, gop_cache = 0x1597860, 
  forwarders = std::vector of length 0, capacity 0, aggregate_stream = 0x1a6a570, handler = 0x95e458, 
  _can_publish = false, atc = false, cache_metadata = 0x0, cache_sh_video = 0x400e640, cache_sh_audio = 0x3414470}
(gdb) p *(SrsServer*)_source[0].handler
$37 = {<ISrsReloadHandler> = {_vptr.ISrsReloadHandler = 0x8953b0 <vtable for SrsServer+368>}, <ISrsSourceHandler> = {
    _vptr.ISrsSourceHandler = 0x895600 <vtable for SrsServer+960>}, <ISrsHlsHandler> = {
    _vptr.ISrsHlsHandler = 0x895660 <vtable for SrsServer+1056>}, <IConnectionManager> = {
    _vptr.IConnectionManager = 0x8956b8 <vtable for SrsServer+1144>}, http_api_mux = 0x95e480, http_server = 
    0x95e510, http_heartbeat = 0x95f5a0, ingester = 0x95f5c0, pid_fd = 6, 
  conns = std::vector of length 600, capacity 1024 = {0x1a70a28, 0x23bb148, 0x22fc878, 0xf428c8, 0x22ec3a8, 0xd31e58, 
    0x21c6e38, 0x2634128, 0x1a11628, 0x2bfae58, 0x2b91378, 0xfe8fd8, 0x104aa78, 0x16d1e58, 0xd7a2f8, 0x2196818, 
    0xe51d68, 0x115fcd8, 0x2623948, 0xe10178, 0xe9c658, 0xd332a8, 0x1e8abf8, 0xd80f38, 0x1f2cc18, 0x21a2ca8, 
    0x23f08a8, 0x17dfbc8, 0x2bb3908, 0x1c736a8, 0x2bf10b8, 0x211ee08, 0x189e9f8, 0x2469978, 0x17bfe78, 0x18e5c88, 
    0x232cd58, 0xf9ced8, 0x216dc18, 0xb32108, 0x21fabd8, 0x288f7c8, 0x3261dc8, 0x3c2e0b8, 0x256b2d8, 0x3ede8b8, 
    0x1c7a1e8, 0x2b253d8, 0x2cda8f8, 0x4824a78, 0x3eadc48, 0x3684058, 0x1872798, 0x1401b68, 0x1fa5f78, 0x23347c8, 
    0x393c2d8, 0x393d8b8, 0xfc4ed8, 0x30cace8, 0x25cbcd8, 0x5000ee8, 0x3403758, 0x40e3578, 0x234f278, 0x1bb01d8, 
    0x393f9e8, 0x14d84e8, 0x3733f48, 0x1927ba8, 0x3a49058, 0x4cf1378, 0x395af48, 0x194e8c8, 0x3a43528, 0xfdf288, 
    0x36ae808, 0x549ad78, 0x157f978, 0x19dc428, 0x2144ff8, 0x4821978, 0x37703b8, 0x4b1b5e8, 0x1283718, 0x47ebc08, 
    0x170aa68, 0x23d6e08, 0x41fa468, 0x24d2728, 0x4a342e8, 0x4870fa8, 0x2dadb08, 0x17048b8, 0x23e6348, 0x3ac9178, 
    0x41e4c88, 0xeb67b8, 0x1bb15f8, 0x3adf098, 0x3e20988, 0x3f75098, 0x2dc76c8, 0x32c1f18, 0x2080c48, 0x4bd8e68, 
    0xae81a8, 0x4980718, 0xcde548, 0x4d30fa8, 0x4e5ad08, 0x105a698, 0x1c71288, 0x1ab2248, 0x4e4cf38, 0x3b09d88, 
    0x3aa03d8, 0x4f6f478, 0x5798198, 0x1f84538, 0x2acc4f8, 0xc21218, 0x2db6268, 0x1b20448, 0x3c2c418, 0x17cb608, 
    0x1142948, 0x3ae9678, 0x2085098, 0x16d0088, 0x393b078, 0x30b2cd8, 0x206a5e8, 0x429fc18, 0x4bcf2d8, 0x33db868, 
    0x2a73b08, 0x2080958, 0x4d06918, 0xd19418, 0x186c9a8, 0x2aa8838, 0x4877ac8, 0x1c70a98, 0x4838338, 0x5da1f78, 
    0x54af678, 0x1b1f3e8, 0x2880e08, 0x36b0f18, 0x1f3f098, 0x1fe5398, 0x4012a98, 0x22d1878, 0x2b7b018, 0x2759928, 
    0x4976078, 0x1a9d638, 0x1bb1cb8, 0x4877188, 0x14dbe58, 0x2067e68, 0x4df73e8, 0x39a3568, 0x1280488, 0x4b1f738, 
    0x2573ae8, 0x3b0c758, 0x40c86d8, 0x4ce4e08, 0x3c3ec28, 0x4449ff8, 0x25e1798, 0x2be4ba8, 0xcd1b68, 0x58a4e38, 
    0x2c9d548, 0xfc8068, 0x3cf6e48, 0x3f5fde8, 0x4f53388, 0x38256c8, 0x1ce6828, 0x2db5dd8, 0x1acfd28, 0x3aeaf48, 
    0x1c507c8, 0xc13d48, 0x35de348, 0x2e41778, 0x12465a8, 0x2d10738, 0x4f55558, 0x399fc18, 0x16f1308, 0x5dd40b8, 
    0x58716e8, 0x378e338, 0x3c89cb8, 0x35d6bd8...}, listeners = std::vector of length 1, capacity 1 = {0x97ba00}, 
  signal_manager = 0x95f1c0, handler = 0x0, signal_reload = false, signal_gmc_stop = false, 
  signal_gracefully_quit = false}
```
当前连接数是600个，这个流的用户数是62个。也没有见到啥问题。

**Comment by winlinvip** [comment]
查看连接的信息：
```
(gdb) p _source[0]
$44 = {<ISrsReloadHandler> = {_vptr.ISrsReloadHandler = 0x896330 <vtable for SrsSource+16>}, static pool = {_M_t = {
      _M_impl = {<std::allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, SrsSource*> > >> = {<__gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, SrsSource*> > >> = {<No data fields>}, <No data fields>}, 
        _M_key_compare = {<std::binary_function<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool>> = {<No data fields>}, <No data fields>}, _M_header = {_M_color = std::_S_red, _M_parent = 0xfe1f00, _M_left = 0x241fa00, _M_right = 0xda8b50}, 
        _M_node_count = 118}}}, _source_id = 62546, _req = 0x1fec450, 
  consumers = std::vector of length 62, capacity 256 = {0x15333c0, 0x2ba0930, 0x393bf70, 0x5bbd090, 0x22db180, 
    0x2abc960, 0x2baf9e0, 0x3f70850, 0x1b27320, 0x41ef190, 0x3c233e0, 0xd16fe0, 0x3599d70, 0xd95cd0, 0x2f50750, 
    0x3d695b0, 0x2ba75d0, 0x35e0ed0, 0x2dc75d0, 0x1a10240, 0x40c4330, 0x21d9c10, 0x2bfa360, 0x4b1b4d0, 0x4e51820, 
    0x475f5f0, 0x2b2af80, 0x5b10ac0, 0x4ca5930, 0x3202290, 0x4d31c90, 0xe03a50, 0x2c27590, 0x2f68240, 0x2acc0e0, 
    0x2e44f20, 0x3aeb250, 0x37b9a40, 0x23e60c0, 0x115d660, 0x41e0530, 0x3776890, 0x3e20f90, 0xd00ba0, 0x3d670a0, 
    0x3b96f70, 0x30adf10, 0x1c9d640, 0x1bb2ff0, 0x1b2cbe0, 0x1a9e790, 0x19dcf80, 0x4f518c0, 0x27d7600, 0x21ed980, 
    0x30ad890, 0x25c3660, 0x3c3eb50, 0x4f52f10, 0x14ea2a0, 0xd94cd0, 0x2be3dd0}, 
  jitter_algorithm = SrsRtmpJitterAlgorithmFULL, mix_correct = false, mix_queue = 0x22798c0, 
  is_monotonically_increase = false, last_packet_time = 1989319, hls = 0x23ea550, dvr = 0x21cc580, 
  encoder = 0x4368690, hds = 0x13fe550, play_edge = 0x3db2e30, publish_edge = 0xf41710, gop_cache = 0x1597860, 
  forwarders = std::vector of length 0, capacity 0, aggregate_stream = 0x1a6a570, handler = 0x95e458, 
  _can_publish = false, atc = false, cache_metadata = 0x0, cache_sh_video = 0x400e640, cache_sh_audio = 0x3414470}

(gdb) x /107xb _source->cache_sh_audio->payload
0x1c70960:	0xb2	0x3e	0x9d	0x1b	0x9a	0x20	0x00	0x01
0x1c70968:	0x7f	0xff	0xff	0xff	0xff	0xff	0xdb	0x6d
0x1c70970:	0xb6	0xdb	0x6d	0xb6	0x89	0x00	0xbf	0xff
0x1c70978:	0xff	0xff	0xff	0xff	0xed	0xb6	0xdb	0x6d
0x1c70980:	0xb6	0xdb	0x42	0x00	0x5f	0xff	0xff	0xff
0x1c70988:	0xff	0xff	0xf6	0xdb	0x6d	0xb6	0xdb	0x6d
0x1c70990:	0xa1	0x00	0x2f	0xff	0xff	0xff	0xff	0xff
0x1c70998:	0xfb	0x6d	0xb6	0xdb	0x6d	0xb6	0xdc	0x3b
0x1c709a0:	0x60	0xab	0xab	0xab	0xab	0xab	0xab	0xab
0x1c709a8:	0xab	0xab	0xab	0x0a	0xba	0xba	0xba	0xba
0x1c709b0:	0xba	0xba	0xba	0xba	0xba	0xb0	0xab	0xab
0x1c709b8:	0xab	0xab	0xab	0xab	0xab	0xab	0xab	0xab
0x1c709c0:	0x0a	0xba	0xba	0xba	0xba	0xba	0xba	0xba
0x1c709c8:	0xba	0xba	0xb7
(gdb) x /45xb _source->cache_sh_video->payload
0x44425d0:	0x17	0x00	0x00	0x00	0x00	0x01	0x4d	0x00
0x44425d8:	0x1e	0xff	0xe1	0x00	0x19	0x67	0x4d	0x40
0x44425e0:	0x1e	0x96	0x54	0x0a	0x0f	0xd8	0x0a	0x84
0x44425e8:	0x00	0x00	0x03	0x00	0x04	0x00	0x00	0x03
0x44425f0:	0x00	0x7a	0x76	0x84	0x89	0xa8	0x01	0x00
0x44425f8:	0x04	0x68	0xce	0x35	0x20
```
这个source即流下面有62个人观看。sequence header貌似也不见有啥异样。除了audio估计是非aac之外。

**Comment by winlinvip** [comment]
2.0.206，我加了一个引用指针到consumer里面，目前从server拿到的连接貌似不太对。更新到206再看看吧。

**Comment by amhoho** [comment]
3.0版本也出现了同样问题
