### ISSUE TITLE
develop分支在cubie上启动即崩溃（crashed immediately on cubieboard）

### ISSUE THREAD

**Issue by phanil** [ossrs/srs#688]
develop分支代码在cubie开发板下编译，启动即崩溃，日志和堆栈信息如下：

```
Starting program: /data/srs/trunk/objs/srs -c conf/srs.conf
[2016-11-12 04:03:10.984][trace][9071][0] XCORE-SRS/3.0.221(OuXuli)
[2016-11-12 04:03:10.985][trace][9071][0] config parse complete
[2016-11-12 04:03:10.986][trace][9071][0] write log to console
[2016-11-12 04:03:10.986][trace][9071][0] SRS/3.0.221(OuXuli), stable is SRS/1.0release
[2016-11-12 04:03:10.986][trace][9071][0] license: The MIT License (MIT), Copyright (c) 2013-2016 SRS(winlin,wenjie.zhao)
[2016-11-12 04:03:10.986][trace][9071][0] authors: winlin,wenjie.zhao
[2016-11-12 04:03:10.986][trace][9071][0] contributors: winlin<winlin@vip.126.com> wenjie.zhao<740936897@qq.com> xiangcheng.liu<liuxc0116@foxmail.com> naijia.liu<youngcow@youngcow.net> alcoholyi<alcoholyi@qq.com> byteman<wangchen2011@gmail.com> chad.wang<chad.wang.cn@gmail.com> suhetao<suhetao@gmail.com> Johnny<fengjihu@163.com> karthikeyan<keyanmca@gmail.com> StevenLiu<lq@chinaffmpeg.org> zhengfl<zhengfl_1989@126.com> tufang14<breadbean1449@gmail.com> allspace<allspace@gmail.com> niesongsong<nie950@gmail.com> rudeb0t<nimrod@themanxgroup.tw> CallMeNP<np.liamg@gmail.com> synote<synote@qq.com> lovecat<littlefawn@163.com> panda1986<542638787@qq.com> YueHonghui<hongf.yue@hotmail.com> 
[2016-11-12 04:03:10.987][trace][9071][0] build: 2016-11-10 18:18:25, configure: --cubie --rtmp-hls --with-ssl --with-ingest --with-http-server --with-http-api --with-http-callback --with-ffmpeg --with-transcode --static, uname: Linux cubie 3.4.79 #1 SMP PREEMPT Wed Jan 28 10:07:33 CST 2015 armv7l armv7l armv7l GNU/Linux
[2016-11-12 04:03:10.987][trace][9071][0] configure detail: --prefix=/usr/local/srs --with-hls --with-hds --with-dvr --without-nginx --with-ssl --with-ffmpeg --with-transcode --with-ingest --with-stat --with-http-callback --with-http-server --without-stream-caster --with-kafka --with-http-api --with-librtmp --without-research --without-utest --without-gperf --without-gmc --without-gmd --without-gmp --without-gcp --without-gprof --without-arm-ubuntu12 --without-mips-ubuntu12 --static --log-trace
[2016-11-12 04:03:10.987][trace][9071][0] cwd=/data/srs/trunk, work_dir=
[2016-11-12 04:03:10.987][trace][9071][0] env MALLOC_CHECK_=1 LIBC_FATAL_STDERR_=1
[2016-11-12 04:03:10.987][trace][9071][0] srs checking config...
[2016-11-12 04:03:10.989][trace][9071][0] ips, local[0] ipv4 192.168.0.8
[2016-11-12 04:03:10.989][trace][9071][0] devices, intranet lo 127.0.0.1, intranet eth0 192.168.0.8
[2016-11-12 04:03:10.989][warn][9071][0][2] stats network use index=0, ip=192.168.0.8
[2016-11-12 04:03:10.989][warn][9071][0][2] stats disk list: sda sdb xvda xvdb 
[2016-11-12 04:03:10.989][trace][9071][0] write log to console
[2016-11-12 04:03:10.990][trace][9071][0] features, rch:on, hls:on, hds:on, hc:on, ha:on, hs:on, hp:on, dvr:on, trans:on, inge:on, kafka:on, stat:on, nginx:off, ff:on, sc:off
[2016-11-12 04:03:10.990][trace][9071][0] SRS on CubieBoardarm, glibc2.19, conf:conf/srs.conf, limit:1000, writev:1024, encoding:little-endian, HZ:100
[2016-11-12 04:03:10.990][trace][9071][0] mw sleep:350ms. mr enabled:on, default:0, sleep:350ms, @see https://github.com/ossrs/srs/issues/241
[2016-11-12 04:03:10.990][trace][9071][0] gc:on, pq:30s, cscc:[0,16), csa:on, tn:on(may hurts performance), ss:auto(guess by merged write)
[2016-11-12 04:03:10.991][trace][9071][0] system default latency in ms: mw(0-350) + mr(0-350) + play-queue(0-30000)
[2016-11-12 04:03:10.991][warn][9071][0][2] SRS 3.0.221 is not stable, please use stable branch 1.0release instead
[2016-11-12 04:03:10.991][trace][9071][0] http: root mount to ./objs/nginx/html
[2016-11-12 04:03:10.992][trace][9071][0] st_init success, use epoll
[2016-11-12 04:03:10.992][trace][9071][100] server main cid=100, pid=9071, ppid=9063, asprocess=0
[2016-11-12 04:03:10.993][trace][9071][100] write pid=9071 to ./objs/srs.pid success!

Program received signal SIGSEGV, Segmentation fault.
_st_thread_main () at sched.c:316
316	{
(gdb) bt
#0  _st_thread_main () at sched.c:316
#1  0x0010c56e in st_thread_create (start=0x10cc8d <st_usleep+172>, arg=0xbefff9a0, 
    joinable=-1224819224, stk_size=65536) at sched.c:591
#2  0x00095e98 in internal::SrsThread::start (this=0x2e6198) at src/app/srs_app_st.cpp:115
#3  0x000933ce in SrsReusableThread::start (this=0x2e6188) at src/app/srs_app_thread.cpp:207
#4  0x000ff84a in SrsTcpListener::listen (this=0x2e6168) at src/app/srs_app_listener.cpp:251
#5  0x00066352 in SrsBufferListener::listen (this=0x2e6148, i=..., p=1935)
    at src/app/srs_app_server.cpp:152
#6  0x0006a6e6 in virtual thunk to SrsBufferListener::listen(std::string, int) ()
    at src/app/srs_app_server.cpp:1579
#7  0x000695de in SrsServer::listen_rtmp (this=0x2c4b68) at src/app/srs_app_server.cpp:1120
#8  0x00067d24 in SrsServer::listen (this=0x2c4b68) at src/app/srs_app_server.cpp:758
#9  0x0010b552 in run_master () at src/main/srs_main_server.cpp:392
#10 0x0010b28c in run () at src/main/srs_main_server.cpp:335
#11 0x0010b1c2 in main (argc=3, argv=0xbefffcf4) at src/main/srs_main_server.cpp:328
(gdb) 
```

**Comment by winlinvip** [comment]
你必须得给ST打patch，参考：https://github.com/ossrs/state-threads
