### ISSUE TITLE
srs目录下出现几个core.xxxx，提取的信息如下

### ISSUE THREAD

**Issue by wuxianlijiang** [ossrs/srs#884]
按空师和成立兄的提示提取如下：
```
gdb -c core.22568 /usr/local/srs/objs/srs
bt

[root@live2 srs]#gdb -c core.22568 /usr/local/srs/objs/srs
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/srs/objs/srs...done.
[New Thread 22568]
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /usr/lib64/libstdc++.so.6...(no debugging symbols found)...done.
Loaded symbols for /usr/lib64/libstdc++.so.6
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libgcc_s.so.1...(no debugging symbols found)...done.
Loaded symbols for /lib64/libgcc_s.so.1
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
Core was generated by `./objs/srs -c ./conf/srs.conf'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f1ea3026258 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib64/libstdc++.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.1.x86_64 libgcc-4.4.7-17.el6.x86_64 libstdc++-4.4.7-17.el6.x86_64
(gdb) bt
#0  0x00007f1ea3026258 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib64/libstdc++.so.6
#1  0x000000000049b34b in SrsHls::dispose (this=0x22442e0)
    at src/app/srs_app_hls.cpp:1166
#2  0x000000000048760f in SrsSource::dispose (this=0x237bdc0)
    at src/app/srs_app_source.cpp:1021
#3  0x000000000048671e in SrsSource::dispose_all ()
    at src/app/srs_app_source.cpp:798
#4  0x000000000047368e in SrsServer::dispose (this=0x1d41180)
    at src/app/srs_app_server.cpp:560
#5  0x0000000000475b2e in SrsServer::cycle (this=0x1d41180)
    at src/app/srs_app_server.cpp:877
#6  0x00000000005276f2 in run_master () at src/main/srs_main_server.cpp:414
#7  0x0000000000527520 in run () at src/main/srs_main_server.cpp:379
#8  0x00000000005271b6 in main (argc=3, argv=0x7ffce30be378)
    at src/main/srs_main_server.cpp:334
(gdb) 

```

**Comment by winlinvip** [comment]
还需要下面的信息：https://github.com/ossrs/srs/wiki/v1_CN_HowToAskQuestion#file-issue

**Comment by winlinvip** [comment]
Can't replay.
